add_requires("nlohmann_json")

-- target("implicit_arrangements")
--     add_rules("library.shared")
--     add_rules("config.indirect_predicates.flags")
--     add_deps("implicit_predicates", "shared_module")
--     add_defines("RELEASE_BRANCH")
--     add_includedirs("./interface", {public = true})
--     add_includedirs("./include")
--     add_files("./src/*.cpp")
--     add_packages("nlohmann_json")
-- target_end()

-- target("implicit_arrangements.LUT.load_test")
--     set_kind("binary")
--     add_rules("config.indirect_predicates.flags")
--     add_defines("SHARED_MODULE=0")
--     add_deps("implicit_arrangements")
--     add_files("./test_lut/main.cpp")
-- target_end()

internal_library("implicit_arrangements", "IA")
    add_rules("config.indirect_predicates.flags")
    add_deps("implicit_predicates", "shared_module")
    add_defines("RELEASE_BRANCH")
    add_packages("nlohmann_json")
    after_build(function (target)
        os.cp(path.join(os.projectdir(), "data", "ia_lut.msgpack"), target:targetdir())
    end)

target("implicit_arrangements.LUT.load_test")
    set_kind("binary")
    add_rules("config.indirect_predicates.flags")
    add_deps("implicit_arrangements")
    add_files("./test_lut/main.cpp")
target_end()