add_requires("nlohmann_json")

internal_library("implicit_arrangements", "IA", os.scriptdir())
    add_rules("config.indirect_predicates.flags")
    add_deps("implicit_predicates", "shared_module")
    add_packages("nlohmann_json")
    after_build(function (target)
        os.cp(path.join(os.projectdir(), "data", "ia_lut.msgpack"), target:targetdir())
    end)

target("implicit_arrangements.LUT.load_test")
    set_kind("binary")
    add_rules("config.indirect_predicates.flags")
    add_deps("implicit_arrangements")
    add_files("./test_lut/main.cpp")
target_end()