add_requires("eigen-latest")

-- target("blobtree_structure")
--     add_rules("library.shared")
--     add_rules("config.indirect_predicates.flags")
--     add_deps("shared_module")
--     add_includedirs("include")
--     add_includedirs("interface", {public = true})
--     add_files("src/*.cpp")
-- target_end()

internal_library("blobtree_structure", "BPE")
    add_rules("config.indirect_predicates.flags")
    add_deps("shared_module")
    add_defines("RELEASE_BRANCH")
    add_packages("eigen-latest", {public = true})
    after_build(function (target)
        os.cp("$(scriptdir)/interface/*.h", target:targetdir())
    end)